pipeline:
  install-pwa:
    group: install
    image: node:8.9.4
    commands:
      - cd eslint-config-quintoandar-pwa
      - npm install --quiet

  install-plugin:
    group: install
    image: node:8.9.4
    commands:
      - cd eslint-plugin-quintoandar-internal
      - npm install --quiet

  lint-pwa:
    group: build
    image: node:8.9.4
    commands:
      - cd eslint-config-quintoandar-pwa
      - npm run lint --unsafe-perm --quiet

  lint-plugin:
    group: build
    image: node:8.9.4
    commands:
      - cd eslint-plugin-quintoandar-internal
      - npm run lint --unsafe-perm --quiet

  test-pwa:
    group: build
    image: node:8.9.4
    commands:
      - cd eslint-config-quintoandar-pwa
      - npm run test --quiet

  test-plugin:
    group: build
    image: node:8.9.4
    commands:
      - cd eslint-plugin-quintoandar-internal
      - npm run test --quiet
